var hoursArray = [' 6 am  || ',' 7 am || ',' 8 am || ',' 9 am || ',' 10 am || ',' 11 am || ',' 12 pm || ',' 1 pm || ',' 2 pm || ',' 3 pm || ',' 4 pm || ',' 5 pm || ',' 6 pm || ',' 7 pm || ',' 8 pm || '];
function getRandomIntInclusive(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
function City(cityName, customerMax, customerMin, avg){
  this.cityName = cityName;
  this.customerMax = customerMax;
  this.customerMin = customerMin;
  this.avg = avg;
  this.cookiesPerHourArray = [];
  this.custPerHourArray = [];
  this.custPerHour = function(){
    console.log('seattle: customers');
    //This 'for' loop fills the custPerHourArray with randomly generated values based on the given statistics.
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCust generates random numbers for the associated array
      var randomCust = Math.floor(Math.random()*(this.customerMax - this.customerMin ) + this.customerMin);
      //Pushes the values generated by randomCust into the array
      this.custPerHourArray.push(randomCust);
      //This displays the values in the browser console
      console.log(this.custPerHourArray);
    }
  };
  this.cookiesPerHour = function(){
    console.log('seattle: cookies');
    //This 'for' loop fills the cookiesPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCookie generates random numbers for the associated array
      var randomCookie = Math.floor(getRandomIntInclusive(this.customerMin, this.customerMax) * this.avg);
      //Pushes the values generated by randomCookie into the array
      this.cookiesPerHourArray.push(randomCookie);
      //This displays the values in the browser console
      console.log(this.cookiesPerHourArray);
    }
  };
  this.totalCookies = function(){
    var totalAmount = 0;
    for(var i=0; i < this.cookiesPerHourArray.length; i++){
      totalAmount += this.cookiesPerHourArray[i];
      // this.totalCookiesArray.push(totalAmount);
    }
    return totalAmount;
  };
}
City.prototype.render = function(){
  var salesData = document.getElementById('salesData');
  var timeLists = document.createElement('tr');
  timeLists.textContent ='Cookies || ';
  for(var i = 0; i < hoursArray.length; i++){
    var timeOfDay = document.createElement('th');
    timeOfDay.textContent = `${hoursArray[i]}`;
    timeLists.appendChild(timeOfDay);
  }
  salesData.appendChild(timeLists);
  //This block of code adds a list item that displays the total amount of cookies bought over the course of the day. It is populated by the "totalCookies" method.
  var total = document.createElement('th');
  total.textContent = 'Total ||';
  timeLists.appendChild(total);
};
var seattle = new City('Seattle', 65, 23, 2.3);
console.log(seattle.cityName);
console.log(seattle.totalCookies());
seattle.custPerHour();
seattle.cookiesPerHour();
seattle.totalCookies();
seattle.render();
