var hoursArray = ['6am','7am','8am','9am','10am','11am','12pm','1pm','2pm','3pm','4pm','5pm','6pm','7pm','8pm'];
var seattle = {
  customerMax: 65,
  customerMin: 23,
  avg: 2.3,
  cookiesPerHourArray: [],
  custPerHourArray: [],
  custPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the custPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCust generates random numbers for the associated array
      var randomCust = Math.floor(Math.random()*(this.customerMax - this.customerMin ) + this.customerMin);
      //Pushes the values generated by randomCust into the array
      this.custPerHourArray.push(randomCust);
      //This displays the values in the browser console
      console.log(this.custPerHourArray);
    }
  },
  cookiesPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the cookiesPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCookie generates random numbers for the associated array
      var randomCookie = Math.floor((Math.random()*(this.customerMax - this.customerMin) + this.customerMin) * this.avg);
      //Pushes the values generated by randomCookie into the array
      this.cookiesPerHourArray.push(randomCookie);
      //This displays the values in the browser console
      console.log(this.cookiesPerHourArray);
    }
  },
};
console.log(seattle.custPerHour());
console.log(seattle.cookiesPerHour());
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var tokyo = {
  customerMax: 24,
  customerMin: 3,
  avg: 1.2,
  cookiesPerHourArray: [],
  custPerHourArray: [],
  custPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the custPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCust generates random numbers for the associated array
      var randomCust = Math.floor(Math.random()*(this.customerMax - this.customerMin ) + this.customerMin);
      //Pushes the values generated by randomCust into the array
      this.custPerHourArray.push(randomCust);
      //This displays the values in the browser console
      console.log(this.custPerHourArray);
    }
  },
  cookiesPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the cookiesPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCookie generates random numbers for the associated array
      var randomCookie = Math.floor((Math.random()*(this.customerMax - this.customerMin) + this.customerMin) * this.avg);
      //Pushes the values generated by randomCookie into the array
      this.cookiesPerHourArray.push(randomCookie);
      //This displays the values in the browser console
      console.log(this.cookiesPerHourArray);
    }
  },
};
console.log(tokyo.custPerHour());
console.log(tokyo.cookiesPerHour());
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var dubai = {
  customerMax: 38,
  customerMin: 11,
  avg: 3.7,
  cookiesPerHourArray: [],
  custPerHourArray: [],
  custPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the custPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCust generates random numbers for the associated array
      var randomCust = Math.floor(Math.random()*(this.customerMax - this.customerMin ) + this.customerMin);
      //Pushes the values generated by randomCust into the array
      this.custPerHourArray.push(randomCust);
      //This displays the values in the browser console
      console.log(this.custPerHourArray);
    }
  },
  cookiesPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the cookiesPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCookie generates random numbers for the associated array
      var randomCookie = Math.floor((Math.random()*(this.customerMax - this.customerMin) + this.customerMin) * this.avg);
      //Pushes the values generated by randomCookie into the array
      this.cookiesPerHourArray.push(randomCookie);
      //This displays the values in the browser console
      console.log(this.cookiesPerHourArray);
    }
  },
};
console.log(dubai.custPerHour());
console.log(dubai.cookiesPerHour());
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var paris = {
  customerMax: 38,
  customerMin: 20,
  avg: 2.3,
  cookiesPerHourArray: [],
  custPerHourArray: [],
  custPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the custPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCust generates random numbers for the associated array
      var randomCust = Math.floor(Math.random()*(this.customerMax - this.customerMin ) + this.customerMin);
      //Pushes the values generated by randomCust into the array
      this.custPerHourArray.push(randomCust);
      //This displays the values in the browser console
      console.log(this.custPerHourArray);
    }
  },
  cookiesPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the cookiesPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCookie generates random numbers for the associated array
      var randomCookie = Math.floor((Math.random()*(this.customerMax - this.customerMin) + this.customerMin) * this.avg);
      //Pushes the values generated by randomCookie into the array
      this.cookiesPerHourArray.push(randomCookie);
      //This displays the values in the browser console
      console.log(this.cookiesPerHourArray);
    }
  },
};
console.log(paris.custPerHour());
console.log(paris.cookiesPerHour());
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var lima = {
  customerMax: 16,
  customerMin: 2,
  avg: 4.6,
  cookiesPerHourArray: [],
  custPerHourArray: [],
  custPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the custPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCust generates random numbers for the associated array
      var randomCust = Math.floor(Math.random()*(this.customerMax - this.customerMin ) + this.customerMin);
      //Pushes the values generated by randomCust into the array
      this.custPerHourArray.push(randomCust);
      //This displays the values in the browser console
      console.log(this.custPerHourArray);
    }
  },
  cookiesPerHour: function(){
    console.log('hello world');
    //This 'for' loop fills the cookiesPerHourArray with randomly generated values
    for(var i = 0; i < hoursArray.length; i++){
      //var randomCookie generates random numbers for the associated array
      var randomCookie = Math.floor((Math.random()*(this.customerMax - this.customerMin) + this.customerMin) * this.avg);
      //Pushes the values generated by randomCookie into the array
      this.cookiesPerHourArray.push(randomCookie);
      //This displays the values in the browser console
      console.log(this.cookiesPerHourArray);
    }
  },
};
console.log(lima.custPerHour());
console.log(lima.cookiesPerHour());
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
